<#

Script for Fibonacci number

Description
_______________
Get the Input from the User

Parameters
_______________
input_val: Integer

Generated By: P Mohamed Riyaz
Genereated on: 10 November 2021

#>
function Fibonacci{
  param([int]$input_val)
  process {
    # Check if input is 0 then it will
    # print incorrect input
    if($input_val -le 0){
      Write-Host("Incorrect input")
    }

    # Check if n is 0
    # then it will return 0
    elseif($input_val -eq 0){
      return 0
    }

    else{
     $current = 0
     $previous = 1
     while ($current -le $input_val) {
       $current
       $current,$previous = ($current + $previous),$current
     }
    }
  }
}


# Use to Function Call, Please Uncomment the below line and pass the arguement.
Fibonacci(50)

# If you want to run the script Please Copy and paste into powershell terminal => Fibonacci -input_val user_input
# Example: Fibonacci -input_val 3
