<#

Script for Find Palindrome

Description
_______________
Get the Input from the User and check the given number is Prime number or not

Parameters
_______________
input_val: Integer

Generated By: P Mohamed Riyaz
Genereated on: 10 November 2021

#>
function FindPrimeNumber{
  param([int]$input_val)
  process {
    $isPrime = $true
    for ($y = 2 ; $y -lt $input_val ; $y++ ) {
      if (($num / $y) -is [int]) {
        Write-Host "$input_val is not a prime number"
        $isPrime = $false
        break
      }
    }
    if ($isPrime -eq $true) {
      Write-Host "$input_val is a prime number"
    }
  }
}

# Use to Function Call, Please Uncomment the below line and pass the arguement.
FindPrimeNumber(3)

# If you want to run the script Please Copy and paste into powershell terminal => FindPrimeNumber -input_val user_input
# Example: FindPrimeNumber -input_val 3