<#

Script for Queue operations

Generated By: P Mohamed Riyaz
Genereated on: 10 November 2021

#>


class Queue{
  [System.Collections.ArrayList]$items
  Queue($i){
    $this.items = $i
  }
  [string] enqueue($input_val) {
    $this.items += $input_val  
    return "Added $input_val"
  }

  [string] dequeue() {
    $count = 0
    $val = $this.items[$count]
    $this.items.Remove($val)
    return "Removed $val"
  }

  [System.Collections.ArrayList] ClearList() {
    $empty_list = $this.items.clear()
    return $empty_list
  }

  [String] GetList() {
    $count = ($this.items.count - 1)
    if($count -lt 0){
      return "List is Empty"
    } else { 
      return ("Queue List: $($this.items)")
    }
  }
}

$items =  @()

# Function Call
$q = [Queue]::new($items)
$q.ClearList()
$q.GetList()
$q.enqueue(10)
$q.enqueue(20)
$q.enqueue(30)
$q.GetList()
$q.dequeue()
$q.dequeue()
# $stack.pop()
$q.GetList()