<#

Script for Stack operations

Generated By: P Mohamed Riyaz
Genereated on: 10 November 2021

#>


class Stack{
  [System.Collections.ArrayList]$items
  Stack($i){
    $this.items = @()
  }
  [string] push($input_val) {
    $this.items += $input_val  
    return "Added $input_val"
  }

  [string] Pop() {
    $count = ($this.items.count - 1)
    $val = $this.items[$count]
    $this.items.Remove($val)
    return "Removed $val"
  }

  
  [System.Collections.ArrayList] ClearList() {
    $empty_list = $this.items.clear()
    return $empty_list
  }

  [String] GetList() {
   $count = ($this.items.count - 1)
    if($count -lt 0){
      return "Stack List is Empty"
    } else { 
      return ("Stack List: $($this.items)")
    }
  }
}

#Function Call
$stack = [Stack]::new($items)
$stack.ClearList()  # Clear the Stack List
$stack.GetList()    # Get the Stack List. It's Empty
$stack.push(20)     # Added 10 into the Stack List
$stack.push(20)     # Added 20 into the Stack List
$stack.push(30)     # Added 30 into the Stack List
$stack.GetList()    # Get the Stack List. Stack List: 10 20 30
$stack.pop()        # Pop up the element from the Stack List. 30 is Removed
$stack.pop()        # Pop up the element from the Stack List. 20 is Removed
# $stack.pop()
$stack.GetList()    # Get the Stack List. Stack List: 10
